### PR TITLE
Added Docker and docker-compose support

### PR DESCRIPTION
**Pull request by pensiero**
With this PR (if you have Docker installed in your machine) you are able to run:
```
docker-compose up -d
```
and see the project up&running on your machine. More info in the updated README.

### CODE REVIEW

**Comment by pensiero** [comment]
@jgl2832 the PR is not ready because I don't have a good connection today, and I didn't try to build the Docker image. Will dop in the next few days, if it works I'll change the status (if it doesn't, I'll check why 💃)

**Review by jgl2832 — APPROVED** [review]
Nice, this is awesome, thanks!!

**Comment by pensiero** [comment]
Development mode works! 🎉 
screenshot 2019-02-12 at 22 15 32

**Comment by pensiero** [comment]
And here the production one!

screenshot 2019-02-12 at 22 40 09

@jgl2832 the only thing that I noticed, is that after running `npm run build` the `package-lock.json` changed, however I didn't commit it

**Comment by pensiero** [comment]
Now we just miss a CD process 💃

**Pull request merged**
